### Invalid Realm
http://localhost:9000/realms/first-real/auth

### Invalid client id [ 1 ]
http://localhost:9000/realms/first-realm/auth

### Invalid client id [ 2 ]
http://localhost:9000/realms/first-realm/auth?client_id=17eQlg7kOopLRhyt8VsApffWByW0XsWM

### Invalid Redirect URI [ 1 ]
http://localhost:9000/realms/first-realm/auth?client_id=17eQlg7kOopLRhyt8VsApffWByW0XsWN

### Invalid Redirect URI [ 2 ]
http://localhost:9000/realms/first-realm/auth?client_id=17eQlg7kOopLRhyt8VsApffWByW0XsWN&redirect_uri=http://localhost:8081/oauth/callbac

### Invalid Response Type [ 1 ]
http://localhost:9000/realms/first-realm/auth?client_id=17eQlg7kOopLRhyt8VsApffWByW0XsWN&redirect_uri=http://localhost:8081/oauth/callback

### Invalid Response Type [ 2 ]
http://localhost:9000/realms/first-realm/auth?client_id=17eQlg7kOopLRhyt8VsApffWByW0XsWN&redirect_uri=http://localhost:8081/oauth/callback&response_type=cod

### Invalid Response Type [ 3 ]
http://localhost:9000/realms/java/auth?client_id=H7WyNTe9FlaIqWzVsR13o1KwdRQnTITV&redirect_uri=http://localhost:8081/oauth/callback&response_type=token

### Invalid Scope [ 1 ]
http://localhost:9000/realms/first-realm/auth?client_id=17eQlg7kOopLRhyt8VsApffWByW0XsWN&redirect_uri=http://localhost:8081/oauth/callback&response_type=code

### Invalid Scope [ 2 ]
http://localhost:9000/realms/first-realm/auth?client_id=17eQlg7kOopLRhyt8VsApffWByW0XsWN&redirect_uri=http://localhost:8081/oauth/callback&response_type=code&scope=email+storage

### Valid Auth URL
http://localhost:9000/realms/java/auth?client_id=VDjRbxXHReJKqjX3jVXjsH148faRYFX5&redirect_uri=http://localhost:8081/oauth/callback&response_type=code&scope=email+profile&state=home

http://localhost:8081/oauth/callback?code=qZyp%2FUBbGVUEOIvDIBhsjj4QYvOGDFssAXp0XJQJfApkX1spHPvXYxjv%2FNshu17rN7A4%2FDnGc9oY1LfmO%2BTkC9mXt3q4eg7Q5DLO5M8M0B0WqFyZEVaAph%2BFSm5jnskS1lgY5m38WGzd78gOlYat0VWWD1tERLHrLXxXmgRt%2BGxf

http://localhost:8081/oauth/callback?code=MppYnJEX58vnIcHAqATJSQdpTEwXZqBkIGj1dA0yVd%2BVMko1lJy7tz4geoOmiPYXlBIPRvGUh%2FiMQmOr1o2RwzdoPcZ9xno6C%2FzOmp%2Fd3ya0Bbs1o%2FYm5bT8iXP3yYlRla37Bl8PZi1eTansNebbyeZPGtqRfnNrFNyFPH0Pf9re&state=home
